version: '3.9'
services:
  back:
    build:
      dockerfile: ./back/Dockerfile
      context: .
    ports:
      - "8000:8000"
    networks:
      - users-system

  mysql:
    image: mysql:5.7.29
    container_name: mysql_laravel
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - users-system

networks:
  users-system: